### ISSUE TITLE
Install .Deb error Inapp tweak

### ISSUE THREAD

**Issue by gaby92** [josephwalden13/tweak-installer#7]
Hi, 

Sorry for my English but when i try install tweak Inapp close terminal windows, attachement screenshot.

thanks for this program

![imagen](https://user-images.githubusercontent.com/35749584/35308444-11333436-00a8-11e8-8ca5-22495a1c775d.png)

**Comment by josephwalden13** [comment]
Please could you send me a copy of  / link to the deb and I’ll look into it

**Comment by gaby92** [comment]
Here examples, thanks

[debs error.zip](https://github.com/josephwalden13/tweak-installer/files/1658208/debs.error.zip)

**Comment by josephwalden13** [comment]
Neither of those are compatible with my tool because they aren't debs... InApp should contain a data.tar file, but instead contains a directory named 'data' which the libraries I use to extract debs refuse to extract. And FluidEnabler should just have been supplied as a zip. It is definitly not a debian file. I have included modified versions that will install with beta9 of my tool which I am going to upload shortly after writing this. 
[FluidEnabler.zip](https://github.com/josephwalden13/tweak-installer/files/1660758/FluidEnabler.zip)
[InApp.zip](https://github.com/josephwalden13/tweak-installer/files/1660759/InApp.zip)

**Comment by josephwalden13** [comment]
Released beta capable of installing the modified zips

**Comment by gaby92** [comment]
thanks, i try again.

**Comment by gaby92** [comment]
well, i try install FluidEnabler and see same error that up screenshot

**Comment by josephwalden13** [comment]
Did you try the files I sent you? Because they work. Also, please don’t rename a zip file to .deb and open error reports that they don’t install. I can’t remember which but at least one of those files was not a deb file and was just an archive named .deb. the files I sent you should work
