### ISSUE TITLE
Error importing roms

### ISSUE THREAD

**Issue by solitude1997** [josephwalden13/tweak-installer#9]
Can't import roms after install with tweak installer. This applies to both gba4ios and delta. It work fine if I install from other sources such as signing service.

**Comment by josephwalden13** [comment]
This could be an issue with sandboxing, which will hopefully be fixed soon by coolstar, however I will take a look

**Comment by josephwalden13** [comment]
Now that the sandbox is gone, I’ll take a look tomorrow to see if anything has changed

**Comment by solitude1997** [comment]
Thank you for taking your time helping

**Comment by josephwalden13** [comment]
Tried with GBA4iOS and Provenance and they are both working. Couldn’t find a copy of Delta though. There is a chance that it is because of the new Electra update that they are working. I’ve tried using a deb of the emulator from a cydia repo so if the ipa doesn’t work you could switch to a deb. Hope you have a good day
